### ISSUE TITLE
Hi, thanks for your reply but I have some problems with GPU memory

### ISSUE THREAD

**Issue by MahmoudSaleh93** [PurdueDigitalTwin/ViT-DD#2]
Hi, thanks for your interest. Please try 
`python3 train.py fit --config configs/vitdd_aucdd.yaml`

_Originally posted by @maysonma in https://github.com/PurdueDigitalTwin/ViT-DD/issues/1#issuecomment-1340224129_

**Comment by MahmoudSaleh93** [comment]
error is "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 304.00 MiB (GPU 0; 14.76 GiB total capacity; 12.85 GiB already allocated; 11.75 MiB free; 13.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"

**Comment by maysonma** [comment]
Hi there,

It looks like you are running into an out-of-memory error on a GPU. This error message indicates that your GPU does not have enough available memory to allocate the required tensor(s). I would suggest reducing the batch size so that the GPU can allocate the tensors without running out of memory. I hope this helps!
