### ISSUE TITLE
Hi, not able to fit the model with given code 

### ISSUE THREAD

**Issue by raki440** [PurdueDigitalTwin/ViT-DD#3]
Hi,
We have ran the cmd "!python /content/ViT-DD/train.py validate -c /content/ViT-DD/configs/vitdd_acudd.yaml" and got into below issue.

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/cli.py:365: LightningDeprecationWarning: LightningCLI's 'save_config_overwrite' init parameter is deprecated from v1.8 and will be removed in v2.0.0. Use `save_config_kwargs={'overwrite': ...}` instead.
  rank_zero_deprecation(
usage: train.py
       [-h]
       [-c CONFIG]
       [--print_config[=flags]]
       {fit,validate,test,predict,tune}
       ...
train.py: error: 'Configuration check failed :: No action for destination key "trainer.weights_save_path" to check its value.'

Need your help to fix same.

**Comment by maysonma** [comment]
@raki440 

Thanks for raising the issue. We will investigate this issue and get back to you soon.

**Comment by raki440** [comment]
@maysonma any update on it?.

**Comment by maysonma** [comment]
Hi there,

It seems you're encountering a deprecated parameter issue in the PyTorch Lightning CLI, as well as a configuration check error. To resolve these, please follow the steps below:

1. Update the Lightning CLI parameter: Open the file `/content/ViT-DD/train.py` and locate the instantiation of `LightningCLI`. Replace the `save_config_overwrite` parameter with `save_config_kwargs={'overwrite': True}`.

2. Address the configuration check error: The error message suggests a problem with the configuration file you're using (`/content/ViT-DD/configs/vitdd_acudd.yaml`). I've tested the code with the latest `Lightning==2.0.1` release and noticed that several `trainer` keys should be removed since they are set to default values in the previous version. These keys include: `num_processes`, `gpus`, `auto_select_gpus`, `tpu_cores`, `ipus, track_grad_norm`, `weights_save_path`, `resume_from_checkpoint`, `auto_lr_find`, `replace_sampler_ddp`, `auto_scale_batch_size`, `amp_backend`, `amp_level`, `move_metrics_to_cpu`, and `multiple_trainloader_mode`.
After making the changes, try running the validation command again.
